#!/usr/bin/env ruby
# frozen_string_literal: true

require 'semversion'
require 'thor'

class App < Thor
  package_name 'semversion'

  desc 'bump', 'Bump the version'
  def bump
    Semversion::BumpVersionCommand.new.exec
  end

  desc 'release ORIGN VERSION?', 'Mark current version released'
  def release(origin, version)
    Semversion::ReleaseCommand.new(origin: origin, version: version).exec
  end

  def self.exit_on_failure?
    true
  end
end

App.start
